/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MayoristasRouteImport } from './routes/mayoristas'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DtfUvRouteImport } from './routes/dtf-uv'
import { Route as DtfTextilRouteImport } from './routes/dtf-textil'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComoEnviarArchivoRouteImport } from './routes/como-enviar-archivo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as ProductosSlugRouteImport } from './routes/productos.$slug'
import { Route as PedidoNumeroRouteImport } from './routes/pedido.$numero'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const MayoristasRoute = MayoristasRouteImport.update({
  id: '/mayoristas',
  path: '/mayoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DtfUvRoute = DtfUvRouteImport.update({
  id: '/dtf-uv',
  path: '/dtf-uv',
  getParentRoute: () => rootRouteImport,
} as any)
const DtfTextilRoute = DtfTextilRouteImport.update({
  id: '/dtf-textil',
  path: '/dtf-textil',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoEnviarArchivoRoute = ComoEnviarArchivoRouteImport.update({
  id: '/como-enviar-archivo',
  path: '/como-enviar-archivo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosSlugRoute = ProductosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductosRoute,
} as any)
const PedidoNumeroRoute = PedidoNumeroRouteImport.update({
  id: '/pedido/$numero',
  path: '/pedido/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-enviar-archivo': typeof ComoEnviarArchivoRoute
  '/contacto': typeof ContactoRoute
  '/dtf-textil': typeof DtfTextilRoute
  '/dtf-uv': typeof DtfUvRoute
  '/faq': typeof FaqRoute
  '/mayoristas': typeof MayoristasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-enviar-archivo': typeof ComoEnviarArchivoRoute
  '/contacto': typeof ContactoRoute
  '/dtf-textil': typeof DtfTextilRoute
  '/dtf-uv': typeof DtfUvRoute
  '/faq': typeof FaqRoute
  '/mayoristas': typeof MayoristasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos': typeof ProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-enviar-archivo': typeof ComoEnviarArchivoRoute
  '/contacto': typeof ContactoRoute
  '/dtf-textil': typeof DtfTextilRoute
  '/dtf-uv': typeof DtfUvRoute
  '/faq': typeof FaqRoute
  '/mayoristas': typeof MayoristasRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-enviar-archivo'
    | '/contacto'
    | '/dtf-textil'
    | '/dtf-uv'
    | '/faq'
    | '/mayoristas'
    | '/admin/login'
    | '/admin/pedidos'
    | '/pedido/$numero'
    | '/productos/$slug'
    | '/productos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-enviar-archivo'
    | '/contacto'
    | '/dtf-textil'
    | '/dtf-uv'
    | '/faq'
    | '/mayoristas'
    | '/admin/login'
    | '/admin/pedidos'
    | '/pedido/$numero'
    | '/productos/$slug'
    | '/productos'
  id:
    | '__root__'
    | '/'
    | '/como-enviar-archivo'
    | '/contacto'
    | '/dtf-textil'
    | '/dtf-uv'
    | '/faq'
    | '/mayoristas'
    | '/admin/login'
    | '/admin/pedidos'
    | '/pedido/$numero'
    | '/productos/$slug'
    | '/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoEnviarArchivoRoute: typeof ComoEnviarArchivoRoute
  ContactoRoute: typeof ContactoRoute
  DtfTextilRoute: typeof DtfTextilRoute
  DtfUvRoute: typeof DtfUvRoute
  FaqRoute: typeof FaqRoute
  MayoristasRoute: typeof MayoristasRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  PedidoNumeroRoute: typeof PedidoNumeroRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mayoristas': {
      id: '/mayoristas'
      path: '/mayoristas'
      fullPath: '/mayoristas'
      preLoaderRoute: typeof MayoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dtf-uv': {
      id: '/dtf-uv'
      path: '/dtf-uv'
      fullPath: '/dtf-uv'
      preLoaderRoute: typeof DtfUvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dtf-textil': {
      id: '/dtf-textil'
      path: '/dtf-textil'
      fullPath: '/dtf-textil'
      preLoaderRoute: typeof DtfTextilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-enviar-archivo': {
      id: '/como-enviar-archivo'
      path: '/como-enviar-archivo'
      fullPath: '/como-enviar-archivo'
      preLoaderRoute: typeof ComoEnviarArchivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$slug': {
      id: '/productos/$slug'
      path: '/$slug'
      fullPath: '/productos/$slug'
      preLoaderRoute: typeof ProductosSlugRouteImport
      parentRoute: typeof ProductosRoute
    }
    '/pedido/$numero': {
      id: '/pedido/$numero'
      path: '/pedido/$numero'
      fullPath: '/pedido/$numero'
      preLoaderRoute: typeof PedidoNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoEnviarArchivoRoute: ComoEnviarArchivoRoute,
  ContactoRoute: ContactoRoute,
  DtfTextilRoute: DtfTextilRoute,
  DtfUvRoute: DtfUvRoute,
  FaqRoute: FaqRoute,
  MayoristasRoute: MayoristasRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  PedidoNumeroRoute: PedidoNumeroRoute,
  ProductosIndexRoute: ProductosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
